#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false
org.gradle.caching=false

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

kotlin.native.cacheKind=none
kotlin.apple.xcodeCompatibility.nowarn=true

kotlin.native.cocoapods.generate.wrapper=true
kotlin.apple.deprecated.allowUsingEmbedAndSignWithCocoaPodsDependencies=true
