target 'iosApp' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'composeApp', :path => '../composeApp'

  # Google Sign In
  pod 'GoogleSignIn', '~> 7.1'
  pod 'AppAuth'
  pod 'GTMAppAuth'
  pod 'GTMSessionFetcher/Core'

  # ✅ Firebase — add these
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end